{% set name = "astronomia" %}
{% set version = "3.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/astronomia-{{ version }}.tar.gz
  sha256: 5f5b5e605b894a8b86f44f66f8f8913cf834659e3838d04cbab048d1fc2dc195

build:
  entry_points:
    - solstice = astronomia.apps.solstice:main
    - check_perihelion = astronomia.apps.check_perihelion:main
    - cronus = astronomia.apps.cronus:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=45
    - setuptools-scm >=6.2
    - wheel
    - pip
  run:
    - python >=3.8
    - cltoolbox
    - dateparser
    - matplotlib-base >=3.3.2
    - numpy
    - odfpy >=1.4.1
    - openpyxl >=3.0.7
    - pandas
    - pint !=0.21
    - pint-pandas
    - pydantic
    - pytables >=3.6.1
    - pyxlsb >=1.0.8
    - scipy
    - tabulate
    - typing-extensions
    - xlrd >=2.0.1
    - xlsxwriter
    - python-calamine

test:
  imports:
    - astronomia
  commands:
    - pip check
    - solstice --help
    - check_perihelion --help
    - cronus --help
  requires:
    - pip

about:
  summary: Library for calculation of ephemeris and other astronomical calculations
  license: GPL-2.0-or-later
  license_file: LICENSE.txt
  home: https://timcera.bitbucket.io/astronomia/docs/index.html

extra:
  recipe-maintainers:
    - timcera
