{% set name = "astronomia" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/astronomia-{{ version }}.tar.gz
  sha256: a6711be1541af0333f778306db6ac209136e9ded7e44ed9a9c5a57b3b9c2fdd6

build:
  entry_points:
    - solstice = astronomia.apps.solstice:main
    - check_perihelion = astronomia.apps.check_perihelion:main
    - cronus = astronomia.apps.cronus:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=45
    - setuptools-scm >=6.2
    - wheel
    - pip
  run:
    - python >=3.8
    - cltoolbox
    - numpy
    - pandas
    - toolbox_utils >=5.0.0,<6.0.0

test:
  imports:
    - astronomia
  commands:
    - pip check
    - solstice --help
    - check_perihelion --help
    - cronus --help
  requires:
    - pip

about:
  summary: Library for calculation of ephemeris and other astronomical calculations
  license: GPL-2.0-or-later
  license_file: LICENSE.txt
  home: https://timcera.bitbucket.io/astronomia/docs/index.html

extra:
  recipe-maintainers:
    - timcera
